# Site settings
title: Scratching code
url: "https://emaren84.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/blog" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Seoul
description: >
  Rinae's DevLog & Translations

# Your information
email: emaren84@gmail.com
author: Rinae
avatar: "//www.gravatar.com/avatar/9524cc46254070122cb0ac9fb286acd3_md5?d=mm&s=135"
profile: Web Developer, Rubyist, Amateur Translator
twitter_username: devRinae
github_username:  emaren84

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: rinaesdevlog   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-redirect-from
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
